db:
  dsn: "root:root@tcp(43.132.192.44:13316)/webook"

migrator:
  pattern: "SRC_ONLY"
  web:
    addr: ":8082"

redis:
  addr: "43.132.192.44:6379"

kafka:
  addrs:
    - "43.132.192.44:9094"

grpc:
  server:
    addr: ":8090"