db:
  src:
    dsn: "root:root@tcp(43.132.215.78:13316)/webook"
  dst:
    dsn: "root:root@tcp(43.132.215.78:13316)/webook_intr"


migrator:
  pattern: "SRC_ONLY"
  web:
    addr: ":8082"

redis:
  addr: "43.132.215.78:6379"

kafka:
  addrs:
    - "43.132.215.78:9094"

grpc:
  server:
    addr: ":8090"