db:
  src:
    dsn: "root:root@tcp(101.33.120.99:13316)/webook"
  dst:
    dsn: "root:root@tcp(101.33.120.99:13316)/webook_intr"


migrator:
  pattern: "SRC_ONLY"
  web:
    addr: ":8082"

redis:
  addr: "101.33.120.99:6379"

kafka:
  addrs:
    - "101.33.120.99:9094"

grpc:
  server:
    addr: ":8090"