GET http://localhost:8080/users/profile
Accept: application/json

###
POST http://localhost:8080/users/edit
Content-Type: application/json

{
  "email": "gopheriilidan@yeah.net",
  "nickname": "GGGG",
  "birthday": "1999-08-02",
  "info": "天行健......君子以自强不息"
}

###
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "gopheriilidan@yeah.net",
  "password": "Abcd@1234#123"
}

###
POST http://localhost:8080/users/signup
Content-Type: application/json

{
  "email": "gopheriilidan@yeah.net",
  "password": "Abcd@1234#123",
  "confirmPassword":"Abcd@1234#123"
}

###
