.PHONY: mock
mock:
	@mockgen -source=C:\Users\Administrator\Desktop\JGEBCamp\webook\internal\service\code.go -package=svcmocks -destination=C:\Users\Administrator\Desktop\JGEBCamp\webook\internal\service\mocks\code_mock.go
	@mockgen -source=C:\Users\Administrator\Desktop\JGEBCamp\webook\internal\service\user.go -package=svcmocks -destination=C:\Users\Administrator\Desktop\JGEBCamp\webook\internal\service\mocks\user_mock.go
	@go mod tidy