apiVersion: apps/v1
kind: Deployment
metadata:
  name: webook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webook
  template:
    metadata:
      labels:
        app: webook
    spec:
      containers:
        - name: webook
          image: ccr.ccs.tencentyun.com/go_k8s/webook:v0.0.3
          ports:
            - containerPort: 8081