apiVersion: v1
kind: PersistentVolume
metadata:
  name: webook-local-pv
spec:
  storageClassName: suibian
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/nmt/data"

