@startuml
    title 找出点赞数前N的数据
    actor user
    participant "web" as web
    participant "service" as svc
    participant "repository" as repo
    participant "dao" as dao
    autonumber
    user -> web: 通过链接访问函数
    note left: 开始
    web -> svc: 调用 svc.FindBestN
    svc -> repo: 调用 repo.FindBestN
    repo -> dao: 调用 dao.FindBestN
    dao --> dao: 完成实数据库操作，返回JSON
    repo <-- dao: 往前返回
    svc <-- repo: 往前返回
    web <-- svc: 往前返回
    user <-- web: 获得经过前端渲染后的结果
@enduml


