db.mysql:
  dsn: "acs:root278803@tcp(101.33.120.99:3308)/webook"

redis:
  addr: "101.33.120.99:6380"

kafka:
  addrs:
    - "localHost: 9094"

grpc:
  client:
    intr:
      addr: "localhost:8090"
      secure: false
      threshold: 100