db.mysql:
  dsn: "acs:root278803@tcp(119.28.64.94:3308)/webook"

redis:
  addr: "119.28.64.94:6380"

kafka:
  addrs:
    - "localHost: 9094"

grpc:
  client:
    intr:
      addr: "localhost:8090"
      secure: false
      threshold: 100