db.mysql:
  dsn: "acs:root278803@tcp(43.132.234.191:3308)/webook"

redis:
  addr: "43.132.234.191:6380"

kafka:
  addrs:
    - "localHost: 9094"

grpc:
  client:
    intr:
      addr: "localhost:8090"
      secure: false
      threshold: 100