// Code generated by MockGen. DO NOT EDIT.
// Source: ./author_dao.go

// Package articlemocks is a generated GoMock package.
package articlemocks

import (
	context "context"
	reflect "reflect"

	article "github.com/Gnoloayoul/JGEBCamp/webook/internal/repository/dao/article"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthorDAO is a mock of AuthorDAO interface.
type MockAuthorDAO struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorDAOMockRecorder
}

// MockAuthorDAOMockRecorder is the mock recorder for MockAuthorDAO.
type MockAuthorDAOMockRecorder struct {
	mock *MockAuthorDAO
}

// NewMockAuthorDAO creates a new mock instance.
func NewMockAuthorDAO(ctrl *gomock.Controller) *MockAuthorDAO {
	mock := &MockAuthorDAO{ctrl: ctrl}
	mock.recorder = &MockAuthorDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorDAO) EXPECT() *MockAuthorDAOMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockAuthorDAO) Insert(ctx context.Context, art article.Article) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, art)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockAuthorDAOMockRecorder) Insert(ctx, art interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockAuthorDAO)(nil).Insert), ctx, art)
}

// UpdateById mocks base method.
func (m *MockAuthorDAO) UpdateById(ctx context.Context, article article.Article) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateById", ctx, article)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateById indicates an expected call of UpdateById.
func (mr *MockAuthorDAOMockRecorder) UpdateById(ctx, article interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateById", reflect.TypeOf((*MockAuthorDAO)(nil).UpdateById), ctx, article)
}
